FROM elixir:1.5.2-alpine

RUN apk update && \
    apk --no-cache --update add libgcc libstdc++ erlang-xmerl && \
    rm -rf /var/cache/apk/*

EXPOSE 4000
ENV PORT=4000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh

ADD s3poller.tar.gz ./
RUN chown -R default ./releases

USER default

ENTRYPOINT ["/opt/app/bin/s3poller"]
